name: NexNum CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Linter
      run: npm run lint

    - name: Run Tests
      # run: npm test # Uncomment when tests are added
      run: echo "Skipping tests for now"

    - name: Build Next.js
      run: npm run build

  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: docker-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Update K8s Manifests
      run: |
        sed -i "s|image: nexnum-app:latest|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" k8s/deployment.yaml

    # Simulating K8s apply (requires KUBECONFIG secret)
    # - name: Deploy to K8s
    #   uses: azure/k8s-set-context@v3
    #   with:
    #     kubeconfig: ${{ secrets.KUBECONFIG }}
    
    # - name: Apply Manifests
    #   run: |
    #     kubectl apply -f k8s/secret-sample.yaml 
    #     kubectl apply -f k8s/service.yaml
    #     kubectl apply -f k8s/deployment.yaml
    #     kubectl apply -f k8s/hpa.yaml
